require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by the Rails when you ran the scaffold generator.

describe MusiciansController do

  def mock_musician(stubs={})
    @mock_musician ||= mock_model(Musician, stubs).as_null_object
  end

  describe "GET index" do
    it "assigns all musicians as @musicians" do
      Musician.stub(:all) { [mock_musician] }
      get :index
      assigns(:musicians).should eq([mock_musician])
    end
  end

  describe "GET show" do
    it "assigns the requested musician as @musician" do
      Musician.stub(:find).with("37") { mock_musician }
      get :show, :id => "37"
      assigns(:musician).should be(mock_musician)
    end
  end

  describe "GET new" do
    it "assigns a new musician as @musician" do
      Musician.stub(:new) { mock_musician }
      get :new
      assigns(:musician).should be(mock_musician)
    end
  end

  describe "GET edit" do
    it "assigns the requested musician as @musician" do
      Musician.stub(:find).with("37") { mock_musician }
      get :edit, :id => "37"
      assigns(:musician).should be(mock_musician)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "assigns a newly created musician as @musician" do
        Musician.stub(:new).with({'these' => 'params'}) { mock_musician(:save => true) }
        post :create, :musician => {'these' => 'params'}
        assigns(:musician).should be(mock_musician)
      end

      it "redirects to the created musician" do
        Musician.stub(:new) { mock_musician(:save => true) }
        post :create, :musician => {}
        response.should redirect_to(musician_url(mock_musician))
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved musician as @musician" do
        Musician.stub(:new).with({'these' => 'params'}) { mock_musician(:save => false) }
        post :create, :musician => {'these' => 'params'}
        assigns(:musician).should be(mock_musician)
      end

      it "re-renders the 'new' template" do
        Musician.stub(:new) { mock_musician(:save => false) }
        post :create, :musician => {}
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested musician" do
        Musician.stub(:find).with("37") { mock_musician }
        mock_musician.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, :id => "37", :musician => {'these' => 'params'}
      end

      it "assigns the requested musician as @musician" do
        Musician.stub(:find) { mock_musician(:update_attributes => true) }
        put :update, :id => "1"
        assigns(:musician).should be(mock_musician)
      end

      it "redirects to the musician" do
        Musician.stub(:find) { mock_musician(:update_attributes => true) }
        put :update, :id => "1"
        response.should redirect_to(musician_url(mock_musician))
      end
    end

    describe "with invalid params" do
      it "assigns the musician as @musician" do
        Musician.stub(:find) { mock_musician(:update_attributes => false) }
        put :update, :id => "1"
        assigns(:musician).should be(mock_musician)
      end

      it "re-renders the 'edit' template" do
        Musician.stub(:find) { mock_musician(:update_attributes => false) }
        put :update, :id => "1"
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested musician" do
      Musician.stub(:find).with("37") { mock_musician }
      mock_musician.should_receive(:destroy)
      delete :destroy, :id => "37"
    end

    it "redirects to the musicians list" do
      Musician.stub(:find) { mock_musician }
      delete :destroy, :id => "1"
      response.should redirect_to(musicians_url)
    end
  end

end
